name: Coletar Dados Cartola

on:
  workflow_dispatch:

  schedule:
    - cron: "*/30 * * * *"

permissions:
  contents: write

jobs:

  coletar:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip

      - name: Executar coleta
        run: |
          python scripts/coletar_cartola.py

      - name: Commit
        run: |

          git config user.name github-actions
          git config user.email github-actions@github.com

          git add .

          git diff --cached --quiet || (
            git commit -m "Atualização automática dos dados do Cartola"
            git push
          )
