/* Cartola Estatístico — UX V2.1: decisão primeiro, detalhes sob demanda */
(function(){
"use strict";
const POS={GOL:"Goleiros",LAT:"Laterais",ZAG:"Zagueiros",MEI:"Meias",ATA:"Atacantes",TEC:"Treinadores"};
let instalado=false,selecionado=null,posicaoRenderizada=null;
const num=(v,p=0)=>Number.isFinite(Number(v))?Number(v):p;
const esc=v=>String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&#039;");
const txt=el=>(el?.textContent||"").replace(/\s+/g," ").trim();
const norm=v=>String(v??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();

function estilo(){
 if(document.getElementById("ceUxV21Style"))return;
 const s=document.createElement("style");s.id="ceUxV21Style";s.textContent=`
 #recomendacoes .hero{grid-template-columns:1fr!important;gap:14px!important;max-width:1180px;margin-inline:auto}#recomendacoes .hero-summary{display:none!important}#recomendacoes .hero-text{max-width:820px;margin-inline:auto;text-align:center}#recomendacoes #playersGrid{max-width:1180px!important;margin-inline:auto!important;width:100%}
 .ce-clean-recs{display:grid;gap:14px;width:100%}.ce-clean-tabs{display:flex;flex-wrap:wrap;justify-content:center;gap:9px;padding:13px;border:1px solid var(--border);border-radius:16px;background:var(--surface)}.ce-clean-player{appearance:none;border:1px solid var(--border);background:var(--surface-soft);color:var(--text);border-radius:999px;padding:10px 14px;cursor:pointer;font:inherit;font-weight:750;display:inline-flex;align-items:center;gap:8px}.ce-clean-player:hover,.ce-clean-player.is-active{border-color:var(--primary);background:var(--primary);color:#fff}.ce-clean-rank{display:inline-grid;place-items:center;min-width:22px;height:22px;border-radius:50%;background:rgba(255,255,255,.14);font-size:10px}.ce-clean-hint{text-align:center;font-size:11px;color:var(--text-soft)}.ce-clean-detail{min-width:0;max-width:980px;margin-inline:auto;width:100%}.ce-clean-detail .player-card{width:100%;max-width:none}
 .ce-decision{margin:14px 18px;padding:16px 18px;border:1px solid rgba(83,216,145,.26);border-radius:15px;background:linear-gradient(135deg,rgba(83,216,145,.10),rgba(83,216,145,.035))}.ce-decision-kicker{font-size:10px;font-weight:850;letter-spacing:.08em;color:#67dfa0;text-transform:uppercase}.ce-decision-title{display:block;margin:5px 0 7px;font-size:19px}.ce-decision p{margin:0;color:var(--text-soft);font-size:12px;line-height:1.55}.ce-decision-chips{display:flex;flex-wrap:wrap;gap:7px;margin-top:11px}.ce-decision-chip{padding:6px 9px;border-radius:999px;background:rgba(127,127,127,.10);font-size:10px;font-weight:750}
 .component-row{border-radius:12px;padding:10px 11px!important;margin:4px 0!important}.component-row.ce-factor-positive{background:rgba(83,216,145,.07)}.component-row.ce-factor-attention{background:rgba(222,185,84,.07)}.component-row.ce-factor-negative{background:rgba(224,98,98,.07)}.ce-factor-status{display:inline-flex!important;align-items:center;gap:5px;padding:4px 8px;border-radius:999px;font-size:10px!important;font-weight:850!important}.ce-factor-status.positive{background:rgba(83,216,145,.15);color:#65dfa0!important}.ce-factor-status.attention{background:rgba(222,185,84,.15);color:#e0bd60!important}.ce-factor-status.negative{background:rgba(224,98,98,.14);color:#ef8b8b!important}.component-row button{border:1px solid var(--border)!important;background:transparent!important;color:var(--text-soft)!important;border-radius:999px!important;padding:5px 9px!important;font-size:10px!important;box-shadow:none!important}.component-row.ce-secondary-factor{display:none}.ce-show-all-factors{display:block;width:100%;margin:12px 0 2px;border:1px solid var(--border);background:var(--surface-soft);color:var(--text);border-radius:10px;padding:9px;font:inherit;font-size:11px;font-weight:750}
 #times .lineup-budget-control{min-height:0!important;height:auto!important;justify-content:flex-start!important;gap:18px!important}.lineup-player-numbers{min-width:110px}.ce-choice-explainer{display:block;margin-top:3px;color:var(--text-soft);font-size:9px;font-weight:650;line-height:1.3}
 #projecoes .v21-toolbar,#projecoes .v21-grid{max-width:1180px!important;margin-inline:auto!important}#projecoes .v21-grid{gap:12px!important}#projecoes .v21-player{background:linear-gradient(145deg,var(--surface),var(--surface-soft))!important;color:var(--text)!important;border-color:var(--border)!important;border-radius:18px!important;padding:18px!important;box-shadow:0 10px 28px rgba(0,0,0,.06)}#projecoes .v21-player h3,#projecoes .v21-proj,#projecoes .v21-kpi strong{color:var(--text)!important}#projecoes .v21-proj{font-size:clamp(24px,3vw,34px)!important}#projecoes .v21-meta,#projecoes .v21-kpi span{color:var(--text-soft)!important;opacity:1!important}#projecoes .v21-badge{background:var(--surface-soft)!important;color:var(--text)!important;border:1px solid var(--border)}#projecoes .v21-toolbar input,#projecoes .v21-toolbar select{background:var(--surface)!important;color:var(--text)!important;border-color:var(--border)!important}
 #historico{min-width:0;overflow-x:hidden}#historico select{min-height:44px!important;background:var(--surface)!important;color:var(--text)!important;border:1px solid var(--border)!important;border-radius:12px!important;padding-inline:12px!important}#historico .ce-history-profile-wrap{max-width:1180px;margin:14px auto 16px;display:grid;gap:8px}#historico .ce-history-profile-label{font-size:10px;text-transform:uppercase;letter-spacing:.08em;color:var(--text-soft);font-weight:800}#historico .ce-history-profile-tabs{display:flex;gap:8px;overflow-x:auto;scrollbar-width:none}#historico .ce-history-profile-tabs button{flex:0 0 auto;border:1px solid var(--border);background:var(--surface);color:var(--text);border-radius:999px;padding:9px 13px;font:inherit;font-weight:750}#historico .ce-history-profile-tabs button.is-active{border-color:var(--primary);background:rgba(83,216,145,.10);color:var(--primary)}#historico canvas,#historico svg{max-width:100%!important;height:auto!important}#historico .history-chart,#historico [class*="chart"]{max-width:100%!important;min-width:0!important;overflow:hidden!important}#historico .history-table-wrap{max-width:100%;overflow-x:auto}.ce-history-help{font-size:11px;color:var(--text-soft)}
 .ce-history-reprocessing{padding:18px;border:1px solid rgba(222,185,84,.28);border-radius:14px;background:rgba(222,185,84,.08);margin:14px 0}.ce-history-reprocessing p{margin:0;color:var(--text-soft);font-size:12px}.ce-tech-hidden{display:none!important}
 .ce-analysis-decisions{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin:16px 0 18px}.ce-analysis-decision{padding:17px;border:1px solid var(--border);border-radius:16px;background:linear-gradient(145deg,var(--surface),var(--surface-soft))}.ce-analysis-decision span{display:block;font-size:9px;letter-spacing:.08em;color:#67dfa0;text-transform:uppercase;font-weight:850}.ce-analysis-decision strong{display:block;margin:6px 0 5px;font-size:18px}.ce-analysis-decision p{margin:0;font-size:11px;color:var(--text-soft);line-height:1.5}.ce-analysis-insight{padding:14px 15px;border:1px solid var(--border);border-radius:14px;background:var(--surface);margin-bottom:12px}.ce-analysis-insight p{margin:4px 0 0;color:var(--text-soft);font-size:11px;line-height:1.5}.ce-tech-toggle{display:inline-flex;margin:10px 0 18px;border:1px solid var(--border);background:var(--surface);color:var(--text-soft);border-radius:999px;padding:8px 12px;font:inherit;font-size:10px;font-weight:750}
 .ce-methodology-final{display:grid;gap:16px;max-width:1180px;margin-inline:auto}.ce-methodology-hero,.ce-methodology-card{padding:19px;border:1px solid var(--border);border-radius:16px;background:var(--surface)}.ce-methodology-hero p,.ce-methodology-card p,.ce-methodology-card li{color:var(--text-soft);line-height:1.58;font-size:12px}.ce-methodology-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.ce-methodology-badge{display:inline-flex;padding:5px 8px;border-radius:999px;background:rgba(83,216,145,.10);color:#67dfa0;font-size:10px;font-weight:850}.ce-methodology-steps{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.ce-methodology-step{padding:14px;border-radius:14px;background:var(--surface-soft);border:1px solid var(--border)}.ce-methodology-step p,.ce-methodology-note{color:var(--text-soft);font-size:11px;line-height:1.5}.ce-methodology-note{padding:12px 14px;border-radius:12px;background:var(--surface-soft)}
 @media(min-width:1200px){.content{padding-left:36px!important;padding-right:36px!important}.main-area{min-width:0}.players-grid,.suggested-lineups-container,#projecoes .v21-grid{max-width:1180px!important;margin-inline:auto!important}}
 @media(max-width:900px){.ce-analysis-decisions,.ce-methodology-grid,.ce-methodology-steps{grid-template-columns:1fr}}
 @media(max-width:700px){.ce-clean-tabs{justify-content:flex-start;overflow-x:auto;flex-wrap:nowrap;padding:10px;scroll-behavior:auto;overscroll-behavior-x:contain;scrollbar-width:none;-webkit-overflow-scrolling:touch}.ce-clean-player{flex:0 0 auto;transition:none!important}.ce-decision{margin:12px 0}.lineup-player-numbers{min-width:88px}#times .lineup-budget-control{min-height:0!important;padding:18px!important;gap:14px!important}#projecoes .v21-player{padding:15px!important}#historico .history-table{min-width:0!important;width:100%!important;display:block}#historico .history-table thead{display:none}#historico .history-table tbody{display:grid;gap:8px}#historico .history-table tr{display:grid;grid-template-columns:1fr 1fr;gap:7px 12px;padding:12px;border:1px solid var(--border);border-radius:12px;background:var(--surface)}#historico .history-table td{display:block!important;border:0!important;padding:0!important;min-width:0!important}#historico .history-table td:first-child{grid-column:1/-1;font-weight:750}#historico .history-table td:not(:first-child)::before{content:attr(data-label);display:block;font-size:8px;text-transform:uppercase;color:var(--text-soft);margin-bottom:2px}}
 `;document.head.appendChild(s);
}
function pAtual(){return typeof obterPosicaoAtiva==="function"?String(obterPosicaoAtiva()).toUpperCase():"GOL"}
function lista(){const l=typeof obterJogadoresDaPosicao==="function"?obterJogadoresDaPosicao(pAtual()):[];return Array.isArray(l)?l:[]}
const jid=j=>String(j?.id??j?.atletaId??j?.atleta_id??j?.apelido??j?.nome??"");
const nome=j=>String(j?.apelido||j?.nome||"Jogador");
function risco(j){const t=norm(j?.riscoTexto??j?.risco??"");return t.includes("alto")?"Risco alto":t.includes("medio")?"Risco médio":"Risco baixo"}
function veredito(j,i){const p=pAtual(),conf=num(j?.confianca??j?.confiancaNumerica),proj=num(j?.projecao??j?.projecaoCalibrada??j?.score),pis=num(j?.piso,proj),r=risco(j);let titulo=i===0?"Forte recomendação":i<=2?"Boa opção":"Alternativa";if(conf<60||r==="Risco alto")titulo=i===0?"Boa opção com cautela":"Aposta com cautela";const m=[];if(num(j?.titularidade??j?.probabilidadeTitular)>=80)m.push("boa segurança de titularidade");if(["GOL","LAT","ZAG"].includes(p)&&num(j?.chanceSG??j?.probabilidadeSG)>=60)m.push("boa perspectiva de SG");if(pis>=4)m.push("piso interessante");if(proj>=8)m.push("projeção forte");return `<section class="ce-decision"><span class="ce-decision-kicker">Decisão do modelo</span><strong class="ce-decision-title">${esc(titulo)}</strong><p><b>${i+1}º entre ${(POS[p]||p).toLowerCase()} indicados.</b> O modelo destaca ${esc(m.slice(0,2).join(" e ")||"combinação competitiva de projeção, contexto e confiança")} nesta rodada.</p><div class="ce-decision-chips"><span class="ce-decision-chip">${proj.toFixed(1)} pts projetados</span><span class="ce-decision-chip">${Math.round(conf)}% confiança</span><span class="ce-decision-chip">${esc(r)}</span></div></section>`}
function fatores(host){const rows=[...host.querySelectorAll(".component-row")];rows.forEach(row=>{const t=norm(txt(row));let c="attention",r="! Atenção";if(t.includes("favoravel")&&!t.includes("desfavoravel")){c="positive";r="✓ Favorável"}else if(t.includes("desfavoravel")||t.includes("risco para esta escolha")){c="negative";r="↓ Desfavorável"}row.classList.add(`ce-factor-${c}`);const alvo=[...row.querySelectorAll("strong,b,span")].find(e=>/favor|aten|desfavor/i.test(txt(e))&&txt(e).length<40);if(alvo){alvo.className=`ce-factor-status ${c}`;alvo.textContent=r}row.querySelectorAll("button").forEach(b=>{if(/ver calculo/i.test(norm(b.textContent)))b.textContent="Como chegou nisso?"})});if(rows.length<=5)return;rows.forEach((r,i)=>r.classList.toggle("ce-secondary-factor",i>=5));if(host.querySelector(".ce-show-all-factors"))return;const b=document.createElement("button");b.type="button";b.className="ce-show-all-factors";b.textContent=`Ver todos os ${rows.length} critérios técnicos`;b.onclick=()=>{const f=rows.some(r=>r.classList.contains("ce-secondary-factor"));rows.forEach((r,i)=>r.classList.toggle("ce-secondary-factor",f?false:i>=5));b.textContent=f?"Mostrar apenas os 5 fatores decisivos":`Ver todos os ${rows.length} critérios técnicos`};rows[4]?.insertAdjacentElement("afterend",b)}
function detalhe(j,host){if(!j||!host||typeof criarCardJogador!=="function")return;const l=lista(),i=Math.max(0,l.findIndex(x=>jid(x)===jid(j))),card=criarCardJogador(j,i+1);host.replaceChildren();if(card)host.appendChild(card);const h=host.querySelector(".player-card-header,.player-header")||host.querySelector(".player-card")?.firstElementChild;if(h)h.insertAdjacentHTML("afterend",veredito(j,i));fatores(host);if(typeof configurarBotoesAnaliseJogador==="function")configurarBotoesAnaliseJogador()}
function sincronizarSelecao(g,l,render=true){const tabs=g.querySelector(".ce-clean-tabs"),x=tabs?.scrollLeft||0;g.querySelectorAll("[data-ce-player]").forEach(b=>{const a=b.dataset.cePlayer===selecionado;b.classList.toggle("is-active",a);b.setAttribute("aria-selected",a?"true":"false");b.tabIndex=a?0:-1});if(tabs)tabs.scrollLeft=x;if(render)detalhe(l.find(j=>jid(j)===selecionado)||l[0],g.querySelector("#ceCleanDetail"))}
function selecionarJogador(g,l,novoId){if(!novoId||novoId===selecionado)return;selecionado=novoId;sincronizarSelecao(g,l,true)}
function recs(){const g=document.getElementById("playersGrid"),l=lista();if(!g||!l.length)return;const p=pAtual();if(!selecionado||!l.some(j=>jid(j)===selecionado))selecionado=jid(l[0]);if(g.querySelector(":scope > .ce-clean-recs")&&posicaoRenderizada===p){sincronizarSelecao(g,l,true);return}posicaoRenderizada=p;g.innerHTML=`<section class="ce-clean-recs"><div class="ce-clean-tabs" role="tablist">${l.map((j,i)=>`<button type="button" role="tab" class="ce-clean-player ${jid(j)===selecionado?"is-active":""}" data-ce-player="${esc(jid(j))}"><span class="ce-clean-rank">${i+1}</span><span>${esc(nome(j))}</span></button>`).join("")}</div><div class="ce-clean-hint">Escolha um jogador. A conclusão vem primeiro; os critérios técnicos ficam sob demanda.</div><div class="ce-clean-detail" id="ceCleanDetail"></div></section>`;sincronizarSelecao(g,l,true);g.querySelector(".ce-clean-tabs")?.addEventListener("click",e=>{const b=e.target.closest("[data-ce-player]");if(b)selecionarJogador(g,lista(),b.dataset.cePlayer)})}
function instalar(){if(instalado)return true;if(typeof exibirJogadoresDaPosicao!=="function"||typeof criarCardJogador!=="function")return false;const o=exibirJogadoresDaPosicao;window.exibirJogadoresDaPosicao=function(){o.apply(this,arguments);posicaoRenderizada=null;recs()};instalado=true;recs();return true}
function topo(){const h=document.querySelector("#recomendacoes .hero-text");if(h&&h.dataset.ceSimplificado!=="1"){h.dataset.ceSimplificado="1";const t=h.querySelector("h2");if(t)t.textContent="Melhores opções da rodada";const ps=[...h.querySelectorAll("p")];if(ps.length)ps.at(-1).textContent="Escolha por posição e veja primeiro a recomendação do modelo. Projeção, risco e contexto aparecem apenas quando ajudam na decisão."}[...document.querySelectorAll("#recomendacoes article,#recomendacoes section,#recomendacoes div")].forEach(el=>{const t=txt(el);if((t.startsWith("O modelo aprende com o que realmente acontece")||t.startsWith("O modelo aprende com o que realmente aconteceu"))&&t.length<1000)el.classList.add("ce-tech-hidden")})}
function patrimonio(){const o=document.querySelector("#times .lineup-budget-control"),a=document.getElementById("v21PatrimonioBox");if(o&&a)a.remove();const i=document.getElementById("lineupBudgetInput");if(i){i.max="200";if(num(i.value,200)>200)i.value="200"}}
function indice(){/* Índice de escolha: comparação interna do modelo; não são pontos do Cartola. */document.querySelectorAll("#times .lineup-player-numbers,#times .lineup-bench-player,#times .lineup-luxury-player").forEach(el=>{if(el.dataset.ceIndice==="2")return;[...el.querySelectorAll("small,span,p")].forEach(n=>{if(/indice de escolha|nota/i.test(norm(txt(n)))&&txt(n).length<80)n.classList.add("ce-tech-hidden")});const h=document.createElement("small");h.className="ce-choice-explainer";h.textContent="Escolhido pela combinação de projeção, risco e orçamento.";el.appendChild(h);el.dataset.ceIndice="2"})}
function historico(){const tab=document.getElementById("historico");if(!tab)return;[...tab.querySelectorAll("article,section,div")].forEach(el=>{const t=txt(el);if((/Laboratório de capitão/i.test(t)||/Torneio de modelos experimentais/i.test(t))&&t.length<1800)el.classList.add("ce-tech-hidden")});const tabela=tab.querySelector(".history-table");if(tabela?.tBodies?.[0]){const rows=[...tabela.tBodies[0].rows].filter(r=>r.cells?.length>=4),zeros=rows.length>=3&&rows.every(r=>Math.abs(num((r.cells[1]?.textContent||"").replace(",",".")))<.0001&&Math.abs(num((r.cells[2]?.textContent||"").replace(",",".")))<.0001),wrap=tabela.closest(".history-table-wrap")||tabela.parentElement;if(zeros&&wrap){wrap.classList.add("ce-tech-hidden");if(!tab.querySelector(".ce-history-reprocessing")){const b=document.createElement("div");b.className="ce-history-reprocessing";b.innerHTML="<strong>Detalhamento em reprocessamento</strong><p>Esta rodada ainda não possui projeção × resultado confiável no formato novo. O histórico antigo com zeros foi ocultado para não confundir.</p>";wrap.before(b)}}const heads=[...tabela.querySelectorAll("thead th")].map(txt);tabela.querySelectorAll("tbody tr").forEach(tr=>[...tr.cells].forEach((td,i)=>{if(heads[i])td.dataset.label=heads[i]}))}if(!tab.querySelector(".ce-history-profile-wrap")){const bs=[...tab.querySelectorAll("button")].filter(b=>/^(conservador|equilibrado|agressivo|recomendado)/i.test(norm(txt(b))));if(bs.length){const pai=bs[0].parentElement,w=document.createElement("div");w.className="ce-history-profile-wrap";w.innerHTML='<span class="ce-history-profile-label">Perfil para comparar</span><div class="ce-history-profile-tabs"></div><p class="ce-history-help">Escolha uma estratégia. Recomendado só aparece como válido quando houver evidência suficiente.</p>';const d=w.querySelector("div");bs.forEach(b=>d.appendChild(b));pai?.before(w);if(pai&&!pai.children.length)pai.remove()}}}
function analise(){const tab=document.getElementById("analise"),res=tab?.querySelector(".analysis-summary"),cards=[...(res?.querySelectorAll(".analysis-card")||[])];if(!tab||!res||!cards.length)return;const val=i=>cards[i]?.querySelector("strong")?.textContent?.trim()||"Em análise";let g=tab.querySelector(".ce-analysis-decisions");if(!g){g=document.createElement("section");g.className="ce-analysis-decisions";res.before(g)}g.innerHTML=`<article class="ce-analysis-decision"><span>Ataque para priorizar</span><strong>${esc(val(0))}</strong><p>Melhor cenário ofensivo. Priorize peças com minutos seguros antes de buscar diferenciais.</p></article><article class="ce-analysis-decision"><span>Defesa para priorizar</span><strong>${esc(val(1))}</strong><p>Melhor leitura de SG. Goleiro, zagueiro e lateral ganham relevância se forem titulares.</p></article><article class="ce-analysis-decision"><span>Jogo para buscar teto</span><strong>${esc(val(2))}</strong><p>Confronto mais indicado para teto. Prefira peças ofensivas e evite empilhar defensores dos dois lados.</p></article>`;if(!tab.querySelector(".ce-analysis-insight")){const x=document.createElement("article");x.className="ce-analysis-insight";x.innerHTML="<b>Como usar esta leitura</b><p>Escolha primeiro o tipo de aposta: ataque, SG ou teto. Depois confirme os nomes na aba Recomendações. Os números brutos ficam apenas para conferência.</p>";g.after(x)}if(!res.dataset.ceTecnico){res.dataset.ceTecnico="1";res.classList.add("ce-tech-hidden");const b=document.createElement("button");b.className="ce-tech-toggle";b.textContent="＋ Ver dados que sustentam os insights";b.onclick=()=>{const o=res.classList.toggle("ce-tech-hidden");b.textContent=o?"＋ Ver dados que sustentam os insights":"− Ocultar dados técnicos"};res.after(b)}const h=[...tab.querySelectorAll("h2,h3")].find(e=>/Força dos clubes na rodada/i.test(txt(e))),bl=h?.closest("section");if(bl&&!bl.dataset.ceTecnicoDetalhe){bl.dataset.ceTecnicoDetalhe="1";bl.classList.add("ce-tech-hidden");const b=document.createElement("button");b.className="ce-tech-toggle";b.textContent="＋ Ver números técnicos dos clubes";b.onclick=()=>bl.classList.toggle("ce-tech-hidden");bl.before(b)}}
function metodologia(){const tab=document.getElementById("metodologia");if(!tab||tab.dataset.ceFinal==="2")return;tab.dataset.ceFinal="2";tab.innerHTML=`<section class="ce-methodology-final"><div class="ce-methodology-hero"><span class="ce-methodology-badge">V2.1 validada</span><h2>Como usar o Cartola Estatístico</h2><p>O site tenta responder uma pergunta simples: <b>quem faz mais sentido escalar nesta rodada?</b> O modelo estima pontuação e risco usando apenas informações disponíveis antes da rodada.</p></div><div class="ce-methodology-steps"><article class="ce-methodology-step"><strong>1. Recomendações</strong><p>Veja os melhores nomes por posição e o motivo.</p></article><article class="ce-methodology-step"><strong>2. Times Sugeridos</strong><p>Monte respeitando patrimônio, formação e limite por clube.</p></article><article class="ce-methodology-step"><strong>3. Cenário e Histórico</strong><p>Confira contexto da rodada e projeção versus resultado real.</p></article></div><div class="ce-methodology-grid"><article class="ce-methodology-card"><h3>O que está ativo</h3><ul><li>RandomForest V2 com walk-forward e anti-leakage.</li><li>Elegibilidade oficial do Cartola e titularidade.</li><li>Até 3 atletas por clube, técnico e 7 formações.</li><li>Patrimônio até C$ 200.</li><li>Capitão 1,5x, banco e Reserva de Luxo no histórico.</li><li>Calibração seletiva de Equilibrado e Agressivo.</li></ul></article><article class="ce-methodology-card"><h3>O que não foi promovido</h3><ul><li>Time Recomendado: não superou o melhor perfil fixo.</li><li>Expected scouts: ganho abaixo do gate.</li><li>Clima observado: diagnóstico, não produção.</li><li>Lateralidade/heatmap e consenso pré-jogo seguem experimentais.</li></ul></article><article class="ce-methodology-card"><h3>Como validamos</h3><p>Para prever uma rodada, o modelo só aprende com rodadas anteriores. O Histórico compara a projeção feita antes da rodada com o resultado real.</p></article><article class="ce-methodology-card"><h3>Limitações e fallback</h3><p>Projeções são probabilísticas. Lesões, cartões e mudanças de última hora geram erro. A V1 permanece preservada para fallback e rollback.</p></article></div><div class="ce-methodology-note">Experimentos reprovados nunca são apresentados como recursos ativos. Detalhes científicos permanecem sob demanda.</div></section>`}
function tudo(){estilo();topo();patrimonio();indice();historico();analise();metodologia()}
let tent=0;const timer=setInterval(()=>{tent++;if(instalar()||tent>50)clearInterval(timer)},100);if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",tudo);else tudo();const observer=new MutationObserver(ms=>{const relevante=ms.some(m=>{const alvo=m.target?.nodeType===1?m.target:m.target?.parentElement;return !alvo?.closest?.("#playersGrid .ce-clean-recs")});if(!relevante)return;clearTimeout(window.__ceUxV21Timer);window.__ceUxV21Timer=setTimeout(()=>{tudo();if(instalado&&!document.querySelector("#playersGrid .ce-clean-recs"))recs()},140)});observer.observe(document.documentElement,{childList:true,subtree:true});window.RecomendacoesUXClean={aplicar:recs};console.info("Cartola Estatístico — UX V2.1 de clareza ativa.");
})();
